config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  resources :users
  resources :microposts,          only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  # Set the root of the webserver 
  root 'static_pages#home'

  # Set static page routes
  get     '/about',   to: 'static_pages#about'
  get     '/help',    to: 'static_pages#help'
  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def about
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="row center">
  <h1><%= yield(:title) %></h1>

  <section>
    The "Microposts" Ruby on Rails webapp was built following the 
    <%= link_to "Ruby on Rails tutorial", 'https://railstutorial.org' %>
    by Michael Hartl.
  </section>

  <section>
    Production environment hosted with 
    <%= link_to "Heroku", 'https://heroku.com' %>
  </section>
  <%= link_to image_tag("heroku.png", alt: "Heroku logo", width: 200),
      'https://heroku.com' %>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<div class="row">
  <h1><%= yield(:title) %></h1>

  <p>
    <%= link_to "Sign up", signup_path %> for an account if you do not have one. You will have to activate it with your email account.
  </p>

  <p>
    <%= link_to "Log in", login_path %> if you have an existing account. 
    You will be able to view and follow other users, and post text and images.

  </p>


</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>

<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the 'Microposts' App</h1>
    <h2>SENG2040 Assignment 04</h2>

    <p>
    <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
    </p>
  </div>

<% end %>